### ISSUE TITLE
CS2 MAP IMPORT ERROR

### ISSUE THREAD

**Issue by L0GiC1337** [andreaskeller96/cs2-import-scripts#2]
I'm trying to import CS:GO JB Map to CS2. 
I've followed everysingle bit of the tutorial & still can't this to operate correctly.
Please any advice?

![image](https://github.com/andreaskeller96/cs2-import-scripts/assets/146876568/cb2f6640-8ba2-4262-995e-b4973d89bfde)

**Comment by andreaskeller96** [comment]
This seems like the vmf is broken, does it compile fine in csgo?

**Comment by L0GiC1337** [comment]
thanks for the fast response, im kinda new to cs2 mapping. could u tell me how i could see if it compiles fine in csgo?

discord: L0GiC1337 if u want

**Comment by andreaskeller96** [comment]
i recommend joining either source engine discord (https://discord.gg/SourceEngine) or mapcore discord (https://discord.gg/XM2C6U4) and asking there

**Comment by C3ylon2558** [comment]
Fix: https://www.youtube.com/watch?v=uF-9n2FQeu4&ab_channel=C3ylon
